// this package is automatically generated by instruction_generator.py
package cpu

import . "memory"


// ld   A, B - A=B
func x78_ld() int {
	SetA(GetB())

	return 1
}

// ld   A, C - A=C
func x79_ld() int {
	SetA(GetC())

	return 1
}

// ld   A, D - A=D
func x7A_ld() int {
	SetA(GetD())

	return 1
}

// ld   A, E - A=E
func x7B_ld() int {
	SetA(GetE())

	return 1
}

// ld   A, H - A=H
func x7C_ld() int {
	SetA(GetH())

	return 1
}

// ld   A, L - A=L
func x7D_ld() int {
	SetA(GetL())

	return 1
}

// ld   A, A - A=A
func x7F_ld() int {
	SetA(GetA())

	return 1
}

// ld   A, %1 - A=%1
func x3E_ld() int {
	SetA(FetchOperand8())

	return 2
}

// ld   B, %1 - B=%1
func x06_ld() int {
	SetB(FetchOperand8())

	return 2
}

// ld   C, %1 - C=%1
func x0E_ld() int {
	SetC(FetchOperand8())

	return 2
}

// ld   D, %1 - D=%1
func x16_ld() int {
	SetD(FetchOperand8())

	return 2
}

// ld   E, %1 - E=%1
func x1E_ld() int {
	SetE(FetchOperand8())

	return 2
}

// ld   H, %1 - H=%1
func x26_ld() int {
	SetH(FetchOperand8())

	return 2
}

// ld   L, %1 - L=%1
func x2E_ld() int {
	SetL(FetchOperand8())

	return 2
}

// ld   A, (HL) - A=(HL)
func x7E_ld() int {
	SetA(Get(GetHL()))

	return 2
}

// ld   B, (HL) - B=(HL)
func x46_ld() int {
	SetB(Get(GetHL()))

	return 2
}

// ld   C, (HL) - C=(HL)
func x4E_ld() int {
	SetC(Get(GetHL()))

	return 2
}

// ld   D, (HL) - D=(HL)
func x56_ld() int {
	SetD(Get(GetHL()))

	return 2
}

// ld   E, (HL) - E=(HL)
func x5E_ld() int {
	SetE(Get(GetHL()))

	return 2
}

// ld   H, (HL) - H=(HL)
func x66_ld() int {
	SetH(Get(GetHL()))

	return 2
}

// ld   L, (HL) - L=(HL)
func x6E_ld() int {
	SetL(Get(GetHL()))

	return 2
}

// ld   (HL), B - [HL]=B
func x70_ld() int {
	Set(GetHL(), GetB())

	return 2
}

// ld   (HL), C - [HL]=C
func x71_ld() int {
	Set(GetHL(), GetC())

	return 2
}

// ld   (HL), D - [HL]=D
func x72_ld() int {
	Set(GetHL(), GetD())

	return 2
}

// ld   (HL), E - [HL]=E
func x73_ld() int {
	Set(GetHL(), GetE())

	return 2
}

// ld   (HL), H - [HL]=H
func x74_ld() int {
	Set(GetHL(), GetH())

	return 2
}

// ld   (HL), L - [HL]=L
func x75_ld() int {
	Set(GetHL(), GetL())

	return 2
}

// ld   (HL), A - [HL]=A
func x77_ld() int {
	Set(GetHL(), GetA())

	return 2
}

// ld   (HL), %1 - [HL]=[NN]
func x36_ld() int {
	Set(GetHL(), FetchOperand8())

	return 3
}

// ld   A, (BC) - A=[BC]
func x0A_ld() int {
	SetA(Get(GetBC()))

	return 2
}

// ld   A, (DE) - A=[DE]
func x1A_ld() int {
	SetA(Get(GetDE()))

	return 2
}

// ld   A, (%2) - A=[NN]
func xFA_ld() int {
	SetA(Get(FetchOperand16()))

	return 4
}

// ld   (BC), A - [BC]=A
func x02_ld() int {
	Set(GetBC(), GetA())

	return 2
}

// ld   (DE), A - [DE]=A
func x12_ld() int {
	Set(GetDE(), GetA())

	return 2
}

// ld   (%2), A - [NN]=A
func xEA_ld() int {
	Set(FetchOperand16(), GetA())

	return 4
}

// ld   A, (FF00+%1) - *read from io-port %1 (memory FF00+%1)
func xF0_ld() int {
	offset := int(FetchOperand8())
    addr := 0xFF00 + uint16(offset)
    value := Get(addr)
    SetA(value)

	return 3
}

// ld   (FF00+%1), A - *write to io-port %1 (memory FF00+%1)
func xE0_ld() int {
	offset := int(FetchOperand8())
    addr := 0xFF00 + uint16(offset)
    value := GetA()
    Set(addr, value)

	return 3
}

// ld   A, (FF00+C) - *read from io-port C (memory FF00+C)
func xF2_ld() int {
	offset := GetC()
    addr := 0xFF00 + uint16(offset)
    value := Get(addr)
    SetA(value)

	return 2
}

// ld   (FF00+C), A - *write to io-port C (memory FF00+C)
func xE2_ld() int {
	offset := GetC()
    addr := 0xFF00 + uint16(offset)
    value := GetA()
    Set(addr, value)

	return 2
}

// ld   BC, %2 - BC=%2
func x01_ld() int {
	SetBC(FetchOperand16())

	return 3
}

// ld   DE, %2 - DE=%2
func x11_ld() int {
	SetDE(FetchOperand16())

	return 3
}

// ld   HL, %2 - HL=%2
func x21_ld() int {
	SetHL(FetchOperand16())

	return 3
}

// ld   SP, %2 - SP=%2
func x31_ld() int {
	SetSP(FetchOperand16())

	return 3
}

// ld   SP, HL - SP=HL
func xF9_ld() int {
	SetSP(GetHL())

	return 2
}

// ld   HL, SP+%s - *HL = SP +/- %s ;%s is 8bit signed number
func xF8_ld() int {
	operand := int(FetchOperand8s())
    result := int(GetSP()) + operand
    SetHL(uint16(result))

    hc := 0
    if operand > 0 {
        if getLowNibble(uint8(operand)) + getLowNibble(getLowBits(GetSP())) > 0xF {
            hc = 1
        } else {
            hc = 0
        }
    }

    SetFlags(result, F_SET_0, F_SET_0, hc, F_SET_IF, F_16bit)

	return 3
}

