// this file is automatically generated by instruction_generator.py
package cpu

import . "common"
import . "memory"

// res  0, B - reset bit 0 of register B
func xCB_80_res() int {
	value := SetBit(GetB(), 0, 0)
	SetB(value)

	return 2
}

// res  1, B - reset bit 1 of register B
func xCB_88_res() int {
	value := SetBit(GetB(), 1, 0)
	SetB(value)

	return 2
}

// res  2, B - reset bit 2 of register B
func xCB_90_res() int {
	value := SetBit(GetB(), 2, 0)
	SetB(value)

	return 2
}

// res  3, B - reset bit 3 of register B
func xCB_98_res() int {
	value := SetBit(GetB(), 3, 0)
	SetB(value)

	return 2
}

// res  4, B - reset bit 4 of register B
func xCB_A0_res() int {
	value := SetBit(GetB(), 4, 0)
	SetB(value)

	return 2
}

// res  5, B - reset bit 5 of register B
func xCB_A8_res() int {
	value := SetBit(GetB(), 5, 0)
	SetB(value)

	return 2
}

// res  6, B - reset bit 6 of register B
func xCB_B0_res() int {
	value := SetBit(GetB(), 6, 0)
	SetB(value)

	return 2
}

// res  7, B - reset bit 7 of register B
func xCB_B8_res() int {
	value := SetBit(GetB(), 7, 0)
	SetB(value)

	return 2
}

// res  0, C - reset bit 0 of register C
func xCB_81_res() int {
	value := SetBit(GetC(), 0, 0)
	SetC(value)

	return 2
}

// res  1, C - reset bit 1 of register C
func xCB_89_res() int {
	value := SetBit(GetC(), 1, 0)
	SetC(value)

	return 2
}

// res  2, C - reset bit 2 of register C
func xCB_91_res() int {
	value := SetBit(GetC(), 2, 0)
	SetC(value)

	return 2
}

// res  3, C - reset bit 3 of register C
func xCB_99_res() int {
	value := SetBit(GetC(), 3, 0)
	SetC(value)

	return 2
}

// res  4, C - reset bit 4 of register C
func xCB_A1_res() int {
	value := SetBit(GetC(), 4, 0)
	SetC(value)

	return 2
}

// res  5, C - reset bit 5 of register C
func xCB_A9_res() int {
	value := SetBit(GetC(), 5, 0)
	SetC(value)

	return 2
}

// res  6, C - reset bit 6 of register C
func xCB_B1_res() int {
	value := SetBit(GetC(), 6, 0)
	SetC(value)

	return 2
}

// res  7, C - reset bit 7 of register C
func xCB_B9_res() int {
	value := SetBit(GetC(), 7, 0)
	SetC(value)

	return 2
}

// res  0, D - reset bit 0 of register D
func xCB_82_res() int {
	value := SetBit(GetD(), 0, 0)
	SetD(value)

	return 2
}

// res  1, D - reset bit 1 of register D
func xCB_8A_res() int {
	value := SetBit(GetD(), 1, 0)
	SetD(value)

	return 2
}

// res  2, D - reset bit 2 of register D
func xCB_92_res() int {
	value := SetBit(GetD(), 2, 0)
	SetD(value)

	return 2
}

// res  3, D - reset bit 3 of register D
func xCB_9A_res() int {
	value := SetBit(GetD(), 3, 0)
	SetD(value)

	return 2
}

// res  4, D - reset bit 4 of register D
func xCB_A2_res() int {
	value := SetBit(GetD(), 4, 0)
	SetD(value)

	return 2
}

// res  5, D - reset bit 5 of register D
func xCB_AA_res() int {
	value := SetBit(GetD(), 5, 0)
	SetD(value)

	return 2
}

// res  6, D - reset bit 6 of register D
func xCB_B2_res() int {
	value := SetBit(GetD(), 6, 0)
	SetD(value)

	return 2
}

// res  7, D - reset bit 7 of register D
func xCB_BA_res() int {
	value := SetBit(GetD(), 7, 0)
	SetD(value)

	return 2
}

// res  0, E - reset bit 0 of register E
func xCB_83_res() int {
	value := SetBit(GetE(), 0, 0)
	SetE(value)

	return 2
}

// res  1, E - reset bit 1 of register E
func xCB_8B_res() int {
	value := SetBit(GetE(), 1, 0)
	SetE(value)

	return 2
}

// res  2, E - reset bit 2 of register E
func xCB_93_res() int {
	value := SetBit(GetE(), 2, 0)
	SetE(value)

	return 2
}

// res  3, E - reset bit 3 of register E
func xCB_9B_res() int {
	value := SetBit(GetE(), 3, 0)
	SetE(value)

	return 2
}

// res  4, E - reset bit 4 of register E
func xCB_A3_res() int {
	value := SetBit(GetE(), 4, 0)
	SetE(value)

	return 2
}

// res  5, E - reset bit 5 of register E
func xCB_AB_res() int {
	value := SetBit(GetE(), 5, 0)
	SetE(value)

	return 2
}

// res  6, E - reset bit 6 of register E
func xCB_B3_res() int {
	value := SetBit(GetE(), 6, 0)
	SetE(value)

	return 2
}

// res  7, E - reset bit 7 of register E
func xCB_BB_res() int {
	value := SetBit(GetE(), 7, 0)
	SetE(value)

	return 2
}

// res  0, H - reset bit 0 of register H
func xCB_84_res() int {
	value := SetBit(GetH(), 0, 0)
	SetH(value)

	return 2
}

// res  1, H - reset bit 1 of register H
func xCB_8C_res() int {
	value := SetBit(GetH(), 1, 0)
	SetH(value)

	return 2
}

// res  2, H - reset bit 2 of register H
func xCB_94_res() int {
	value := SetBit(GetH(), 2, 0)
	SetH(value)

	return 2
}

// res  3, H - reset bit 3 of register H
func xCB_9C_res() int {
	value := SetBit(GetH(), 3, 0)
	SetH(value)

	return 2
}

// res  4, H - reset bit 4 of register H
func xCB_A4_res() int {
	value := SetBit(GetH(), 4, 0)
	SetH(value)

	return 2
}

// res  5, H - reset bit 5 of register H
func xCB_AC_res() int {
	value := SetBit(GetH(), 5, 0)
	SetH(value)

	return 2
}

// res  6, H - reset bit 6 of register H
func xCB_B4_res() int {
	value := SetBit(GetH(), 6, 0)
	SetH(value)

	return 2
}

// res  7, H - reset bit 7 of register H
func xCB_BC_res() int {
	value := SetBit(GetH(), 7, 0)
	SetH(value)

	return 2
}

// res  0, L - reset bit 0 of register L
func xCB_85_res() int {
	value := SetBit(GetL(), 0, 0)
	SetL(value)

	return 2
}

// res  1, L - reset bit 1 of register L
func xCB_8D_res() int {
	value := SetBit(GetL(), 1, 0)
	SetL(value)

	return 2
}

// res  2, L - reset bit 2 of register L
func xCB_95_res() int {
	value := SetBit(GetL(), 2, 0)
	SetL(value)

	return 2
}

// res  3, L - reset bit 3 of register L
func xCB_9D_res() int {
	value := SetBit(GetL(), 3, 0)
	SetL(value)

	return 2
}

// res  4, L - reset bit 4 of register L
func xCB_A5_res() int {
	value := SetBit(GetL(), 4, 0)
	SetL(value)

	return 2
}

// res  5, L - reset bit 5 of register L
func xCB_AD_res() int {
	value := SetBit(GetL(), 5, 0)
	SetL(value)

	return 2
}

// res  6, L - reset bit 6 of register L
func xCB_B5_res() int {
	value := SetBit(GetL(), 6, 0)
	SetL(value)

	return 2
}

// res  7, L - reset bit 7 of register L
func xCB_BD_res() int {
	value := SetBit(GetL(), 7, 0)
	SetL(value)

	return 2
}

// res  0, A - reset bit 0 of register A
func xCB_87_res() int {
	value := SetBit(GetA(), 0, 0)
	SetA(value)

	return 2
}

// res  1, A - reset bit 1 of register A
func xCB_8F_res() int {
	value := SetBit(GetA(), 1, 0)
	SetA(value)

	return 2
}

// res  2, A - reset bit 2 of register A
func xCB_97_res() int {
	value := SetBit(GetA(), 2, 0)
	SetA(value)

	return 2
}

// res  3, A - reset bit 3 of register A
func xCB_9F_res() int {
	value := SetBit(GetA(), 3, 0)
	SetA(value)

	return 2
}

// res  4, A - reset bit 4 of register A
func xCB_A7_res() int {
	value := SetBit(GetA(), 4, 0)
	SetA(value)

	return 2
}

// res  5, A - reset bit 5 of register A
func xCB_AF_res() int {
	value := SetBit(GetA(), 5, 0)
	SetA(value)

	return 2
}

// res  6, A - reset bit 6 of register A
func xCB_B7_res() int {
	value := SetBit(GetA(), 6, 0)
	SetA(value)

	return 2
}

// res  7, A - reset bit 7 of register A
func xCB_BF_res() int {
	value := SetBit(GetA(), 7, 0)
	SetA(value)

	return 2
}

// res  0, (HL) - reset bit 0 of [HL]
func xCB_86_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 0, 0)
	Set(addr, value)

	return 4
}

// res  1, (HL) - reset bit 1 of [HL]
func xCB_8E_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 1, 0)
	Set(addr, value)

	return 4
}

// res  2, (HL) - reset bit 2 of [HL]
func xCB_96_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 2, 0)
	Set(addr, value)

	return 4
}

// res  3, (HL) - reset bit 3 of [HL]
func xCB_9E_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 3, 0)
	Set(addr, value)

	return 4
}

// res  4, (HL) - reset bit 4 of [HL]
func xCB_A6_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 4, 0)
	Set(addr, value)

	return 4
}

// res  5, (HL) - reset bit 5 of [HL]
func xCB_AE_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 5, 0)
	Set(addr, value)

	return 4
}

// res  6, (HL) - reset bit 6 of [HL]
func xCB_B6_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 6, 0)
	Set(addr, value)

	return 4
}

// res  7, (HL) - reset bit 7 of [HL]
func xCB_BE_res() int {
	addr := GetHL()
	value := SetBit(Get(addr), 7, 0)
	Set(addr, value)

	return 4
}

