// this file is automatically generated by instruction_generator.py
package cpu

import . "memory"


// rlc  B - *rotate B left
func xCB_00_rlc() int {
	value := GetB()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetB(value)

	return 2
}

// rlc  C - *rotate C left
func xCB_01_rlc() int {
	value := GetC()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetC(value)

	return 2
}

// rlc  D - *rotate D left
func xCB_02_rlc() int {
	value := GetD()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetD(value)

	return 2
}

// rlc  E - *rotate E left
func xCB_03_rlc() int {
	value := GetE()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetE(value)

	return 2
}

// rlc  H - *rotate H left
func xCB_04_rlc() int {
	value := GetH()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetH(value)

	return 2
}

// rlc  L - *rotate L left
func xCB_05_rlc() int {
	value := GetL()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetL(value)

	return 2
}

// rlc  (HL) - *rotate [HL] left
func xCB_06_rlc() int {
	value := Get(GetHL())
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	Set(GetHL(), value)

	return 4
}

// rlc  A - *rotate A left
func xCB_07_rlc() int {
	value := GetA()
	msb := GetBit(value, 7)

	value = value << 1
	value = SetBit(value, 0, msb)

	SetFlagCy(msb == 1)
	SetFlagZf(value == 0)
	SetFlagN(false)
	SetFlagH(false)

	SetA(value)

	return 2
}

