// this file is automatically generated by instruction_generator.py
package cpu


// rst  00 - call to 0x0000
func xC7_rst() int {
	Call(0x0000)

	return 4
}

// rst  08 - call to 0x0008
func xCF_rst() int {
	Call(0x0008)

	return 4
}

// rst  10 - call to 0x0010
func xD7_rst() int {
	Call(0x0010)

	return 4
}

// rst  18 - call to 0x0018
func xDF_rst() int {
	Call(0x0018)

	return 4
}

// rst  20 - call to 0x0020
func xE7_rst() int {
	Call(0x0020)

	return 4
}

// rst  28 - call to 0x0028
func xEF_rst() int {
	Call(0x0028)

	return 4
}

// rst  30 - call to 0x0030
func xF7_rst() int {
	Call(0x0030)

	return 4
}

// rst  38 - call to 0x0038
func xFF_rst() int {
	Call(0x0038)

	return 4
}

