// this package is automatically generated by instruction_generator.py
package cpu

import . "memory"


// set  0, B - set bit 0 of register B
func xCB_C0_set() int {
	value := SetBit(GetB(), 0, 1)
	SetB(value)

	return 2
}

// set  1, B - set bit 1 of register B
func xCB_C8_set() int {
	value := SetBit(GetB(), 1, 1)
	SetB(value)

	return 2
}

// set  2, B - set bit 2 of register B
func xCB_D0_set() int {
	value := SetBit(GetB(), 2, 1)
	SetB(value)

	return 2
}

// set  3, B - set bit 3 of register B
func xCB_D8_set() int {
	value := SetBit(GetB(), 3, 1)
	SetB(value)

	return 2
}

// set  4, B - set bit 4 of register B
func xCB_E0_set() int {
	value := SetBit(GetB(), 4, 1)
	SetB(value)

	return 2
}

// set  5, B - set bit 5 of register B
func xCB_E8_set() int {
	value := SetBit(GetB(), 5, 1)
	SetB(value)

	return 2
}

// set  6, B - set bit 6 of register B
func xCB_F0_set() int {
	value := SetBit(GetB(), 6, 1)
	SetB(value)

	return 2
}

// set  7, B - set bit 7 of register B
func xCB_F8_set() int {
	value := SetBit(GetB(), 7, 1)
	SetB(value)

	return 2
}

// set  0, C - set bit 0 of register C
func xCB_C1_set() int {
	value := SetBit(GetC(), 0, 1)
	SetC(value)

	return 2
}

// set  1, C - set bit 1 of register C
func xCB_C9_set() int {
	value := SetBit(GetC(), 1, 1)
	SetC(value)

	return 2
}

// set  2, C - set bit 2 of register C
func xCB_D1_set() int {
	value := SetBit(GetC(), 2, 1)
	SetC(value)

	return 2
}

// set  3, C - set bit 3 of register C
func xCB_D9_set() int {
	value := SetBit(GetC(), 3, 1)
	SetC(value)

	return 2
}

// set  4, C - set bit 4 of register C
func xCB_E1_set() int {
	value := SetBit(GetC(), 4, 1)
	SetC(value)

	return 2
}

// set  5, C - set bit 5 of register C
func xCB_E9_set() int {
	value := SetBit(GetC(), 5, 1)
	SetC(value)

	return 2
}

// set  6, C - set bit 6 of register C
func xCB_F1_set() int {
	value := SetBit(GetC(), 6, 1)
	SetC(value)

	return 2
}

// set  7, C - set bit 7 of register C
func xCB_F9_set() int {
	value := SetBit(GetC(), 7, 1)
	SetC(value)

	return 2
}

// set  0, D - set bit 0 of register D
func xCB_C2_set() int {
	value := SetBit(GetD(), 0, 1)
	SetD(value)

	return 2
}

// set  1, D - set bit 1 of register D
func xCB_CA_set() int {
	value := SetBit(GetD(), 1, 1)
	SetD(value)

	return 2
}

// set  2, D - set bit 2 of register D
func xCB_D2_set() int {
	value := SetBit(GetD(), 2, 1)
	SetD(value)

	return 2
}

// set  3, D - set bit 3 of register D
func xCB_DA_set() int {
	value := SetBit(GetD(), 3, 1)
	SetD(value)

	return 2
}

// set  4, D - set bit 4 of register D
func xCB_E2_set() int {
	value := SetBit(GetD(), 4, 1)
	SetD(value)

	return 2
}

// set  5, D - set bit 5 of register D
func xCB_EA_set() int {
	value := SetBit(GetD(), 5, 1)
	SetD(value)

	return 2
}

// set  6, D - set bit 6 of register D
func xCB_F2_set() int {
	value := SetBit(GetD(), 6, 1)
	SetD(value)

	return 2
}

// set  7, D - set bit 7 of register D
func xCB_FA_set() int {
	value := SetBit(GetD(), 7, 1)
	SetD(value)

	return 2
}

// set  0, E - set bit 0 of register E
func xCB_C3_set() int {
	value := SetBit(GetE(), 0, 1)
	SetE(value)

	return 2
}

// set  1, E - set bit 1 of register E
func xCB_CB_set() int {
	value := SetBit(GetE(), 1, 1)
	SetE(value)

	return 2
}

// set  2, E - set bit 2 of register E
func xCB_D3_set() int {
	value := SetBit(GetE(), 2, 1)
	SetE(value)

	return 2
}

// set  3, E - set bit 3 of register E
func xCB_DB_set() int {
	value := SetBit(GetE(), 3, 1)
	SetE(value)

	return 2
}

// set  4, E - set bit 4 of register E
func xCB_E3_set() int {
	value := SetBit(GetE(), 4, 1)
	SetE(value)

	return 2
}

// set  5, E - set bit 5 of register E
func xCB_EB_set() int {
	value := SetBit(GetE(), 5, 1)
	SetE(value)

	return 2
}

// set  6, E - set bit 6 of register E
func xCB_F3_set() int {
	value := SetBit(GetE(), 6, 1)
	SetE(value)

	return 2
}

// set  7, E - set bit 7 of register E
func xCB_FB_set() int {
	value := SetBit(GetE(), 7, 1)
	SetE(value)

	return 2
}

// set  0, H - set bit 0 of register H
func xCB_C4_set() int {
	value := SetBit(GetH(), 0, 1)
	SetH(value)

	return 2
}

// set  1, H - set bit 1 of register H
func xCB_CC_set() int {
	value := SetBit(GetH(), 1, 1)
	SetH(value)

	return 2
}

// set  2, H - set bit 2 of register H
func xCB_D4_set() int {
	value := SetBit(GetH(), 2, 1)
	SetH(value)

	return 2
}

// set  3, H - set bit 3 of register H
func xCB_DC_set() int {
	value := SetBit(GetH(), 3, 1)
	SetH(value)

	return 2
}

// set  4, H - set bit 4 of register H
func xCB_E4_set() int {
	value := SetBit(GetH(), 4, 1)
	SetH(value)

	return 2
}

// set  5, H - set bit 5 of register H
func xCB_EC_set() int {
	value := SetBit(GetH(), 5, 1)
	SetH(value)

	return 2
}

// set  6, H - set bit 6 of register H
func xCB_F4_set() int {
	value := SetBit(GetH(), 6, 1)
	SetH(value)

	return 2
}

// set  7, H - set bit 7 of register H
func xCB_FC_set() int {
	value := SetBit(GetH(), 7, 1)
	SetH(value)

	return 2
}

// set  0, L - set bit 0 of register L
func xCB_C5_set() int {
	value := SetBit(GetL(), 0, 1)
	SetL(value)

	return 2
}

// set  1, L - set bit 1 of register L
func xCB_CD_set() int {
	value := SetBit(GetL(), 1, 1)
	SetL(value)

	return 2
}

// set  2, L - set bit 2 of register L
func xCB_D5_set() int {
	value := SetBit(GetL(), 2, 1)
	SetL(value)

	return 2
}

// set  3, L - set bit 3 of register L
func xCB_DD_set() int {
	value := SetBit(GetL(), 3, 1)
	SetL(value)

	return 2
}

// set  4, L - set bit 4 of register L
func xCB_E5_set() int {
	value := SetBit(GetL(), 4, 1)
	SetL(value)

	return 2
}

// set  5, L - set bit 5 of register L
func xCB_ED_set() int {
	value := SetBit(GetL(), 5, 1)
	SetL(value)

	return 2
}

// set  6, L - set bit 6 of register L
func xCB_F5_set() int {
	value := SetBit(GetL(), 6, 1)
	SetL(value)

	return 2
}

// set  7, L - set bit 7 of register L
func xCB_FD_set() int {
	value := SetBit(GetL(), 7, 1)
	SetL(value)

	return 2
}

// set  0, A - set bit 0 of register A
func xCB_C7_set() int {
	value := SetBit(GetA(), 0, 1)
	SetA(value)

	return 2
}

// set  1, A - set bit 1 of register A
func xCB_CF_set() int {
	value := SetBit(GetA(), 1, 1)
	SetA(value)

	return 2
}

// set  2, A - set bit 2 of register A
func xCB_D7_set() int {
	value := SetBit(GetA(), 2, 1)
	SetA(value)

	return 2
}

// set  3, A - set bit 3 of register A
func xCB_DF_set() int {
	value := SetBit(GetA(), 3, 1)
	SetA(value)

	return 2
}

// set  4, A - set bit 4 of register A
func xCB_E7_set() int {
	value := SetBit(GetA(), 4, 1)
	SetA(value)

	return 2
}

// set  5, A - set bit 5 of register A
func xCB_EF_set() int {
	value := SetBit(GetA(), 5, 1)
	SetA(value)

	return 2
}

// set  6, A - set bit 6 of register A
func xCB_F7_set() int {
	value := SetBit(GetA(), 6, 1)
	SetA(value)

	return 2
}

// set  7, A - set bit 7 of register A
func xCB_FF_set() int {
	value := SetBit(GetA(), 7, 1)
	SetA(value)

	return 2
}

// set  0, (HL) - set bit 0 of [HL]
func xCB_C6_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 0, 1)
	Set(addr, value)

	return 4
}

// set  1, (HL) - set bit 1 of [HL]
func xCB_CE_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 1, 1)
	Set(addr, value)

	return 4
}

// set  2, (HL) - set bit 2 of [HL]
func xCB_D6_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 2, 1)
	Set(addr, value)

	return 4
}

// set  3, (HL) - set bit 3 of [HL]
func xCB_DE_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 3, 1)
	Set(addr, value)

	return 4
}

// set  4, (HL) - set bit 4 of [HL]
func xCB_E6_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 4, 1)
	Set(addr, value)

	return 4
}

// set  5, (HL) - set bit 5 of [HL]
func xCB_EE_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 5, 1)
	Set(addr, value)

	return 4
}

// set  6, (HL) - set bit 6 of [HL]
func xCB_F6_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 6, 1)
	Set(addr, value)

	return 4
}

// set  7, (HL) - set bit 7 of [HL]
func xCB_FE_set() int {
	addr := GetHL()
	value := SetBit(Get(addr), 7, 1)
	Set(addr, value)

	return 4
}

