// this file is automatically generated by instruction_generator.py
package cpu

import . "memory"

// swap B - exchange B low/hi-nibble
func xCB_30_swap() int {
	SetB(Swap(GetB()))

	return 2
}

// swap C - exchange C low/hi-nibble
func xCB_31_swap() int {
	SetC(Swap(GetC()))

	return 2
}

// swap D - exchange D low/hi-nibble
func xCB_32_swap() int {
	SetD(Swap(GetD()))

	return 2
}

// swap E - exchange E low/hi-nibble
func xCB_33_swap() int {
	SetE(Swap(GetE()))

	return 2
}

// swap H - exchange H low/hi-nibble
func xCB_34_swap() int {
	SetH(Swap(GetH()))

	return 2
}

// swap L - exchange L low/hi-nibble
func xCB_35_swap() int {
	SetL(Swap(GetL()))

	return 2
}

// swap (HL) - exchange [HL] low/hi-nibble
func xCB_36_swap() int {
	addr := GetHL()
	Write(addr, Swap(Get(addr)))

	return 4
}

// swap A - exchange A low/hi-nibble
func xCB_37_swap() int {
	SetA(Swap(GetA()))

	return 2
}
